"""
AI-Assisted STRIDE Threat Model Generator
Author: AM Consulting
Description: Takes a system description and generates a structured STRIDE
             threat model using the Anthropic Claude API.
"""

import anthropic
import json
import os
import sys
from datetime import datetime


def load_api_key() -> str:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "ANTHROPIC_API_KEY not set. Add it to your environment variables."
        )
    return api_key


def build_prompt(system_description: str) -> str:
    return f"""
You are a senior cybersecurity engineer specialising in threat modelling.

A user has provided the following system description:

---
{system_description}
---

Perform a full STRIDE threat model analysis on this system.

For each STRIDE category (Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege):
- Identify 2-3 realistic threats specific to this system
- Assign a severity: Critical / High / Medium / Low
- Suggest a concrete mitigation

Return your response ONLY as a valid JSON object in this exact structure:

{{
  "system_summary": "one sentence summary of the system",
  "threats": [
    {{
      "category": "Spoofing",
      "threat": "description of threat",
      "severity": "High",
      "mitigation": "concrete mitigation step"
    }}
  ],
  "overall_risk_rating": "Critical | High | Medium | Low",
  "analyst_notes": "2-3 sentences of overall observations"
}}

Return JSON only. No markdown, no explanation outside the JSON.
"""


def generate_threat_model(system_description: str) -> dict:
    client = anthropic.Anthropic(api_key=load_api_key())

    print("[*] Sending system description to Claude API...")

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2000,
        messages=[
            {"role": "user", "content": build_prompt(system_description)}
        ]
    )

    raw = message.content[0].text.strip()

    try:
        result = json.loads(raw)
    except json.JSONDecodeError:
        print("[!] Warning: Could not parse JSON response. Returning raw output.")
        return {"raw_output": raw}

    return result


def save_report(result: dict, system_description: str, output_dir: str = "sample_output"):
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    md_path = os.path.join(output_dir, f"threat_model_{timestamp}.md")

    lines = []
    lines.append("# STRIDE Threat Model Report")
    lines.append(f"\n**Generated:** {datetime.now().strftime('%d %B %Y %H:%M')}")
    lines.append(f"\n**Tool:** AI Threat Model Generator | AM Consulting")

    lines.append("\n---\n")
    lines.append("## System Description")
    lines.append(f"\n{system_description}\n")

    if "raw_output" in result:
        lines.append("## Raw Output\n")
        lines.append(result["raw_output"])
    else:
        lines.append(f"**System Summary:** {result.get('system_summary', 'N/A')}\n")
        lines.append(f"**Overall Risk Rating:** `{result.get('overall_risk_rating', 'N/A')}`\n")

        lines.append("\n---\n")
        lines.append("## STRIDE Threat Analysis\n")

        severity_order = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
        threats = sorted(
            result.get("threats", []),
            key=lambda x: severity_order.get(x.get("severity", "Low"), 4)
        )

        for t in threats:
            sev = t.get("severity", "N/A")
            lines.append(f"### [{sev}] {t.get('category', 'N/A')} — {t.get('threat', 'N/A')}")
            lines.append(f"\n**Mitigation:** {t.get('mitigation', 'N/A')}\n")

        lines.append("\n---\n")
        lines.append("## Analyst Notes")
        lines.append(f"\n{result.get('analyst_notes', 'N/A')}\n")

    lines.append("\n---")
    lines.append("*Report generated by AI Threat Model Generator — AM Consulting*")

    with open(md_path, "w") as f:
        f.write("\n".join(lines))

    print(f"[+] Report saved to: {md_path}")
    return md_path


def print_summary(result: dict):
    if "raw_output" in result:
        print("\n--- RAW OUTPUT ---")
        print(result["raw_output"])
        return

    print("\n========================================")
    print("  STRIDE THREAT MODEL — SUMMARY")
    print("========================================")
    print(f"System  : {result.get('system_summary', 'N/A')}")
    print(f"Risk    : {result.get('overall_risk_rating', 'N/A')}")
    print(f"Threats : {len(result.get('threats', []))}")
    print("----------------------------------------")

    for t in result.get("threats", []):
        print(f"[{t.get('severity')}] {t.get('category')} — {t.get('threat')}")

    print("----------------------------------------")
    print(f"Notes: {result.get('analyst_notes', 'N/A')}")
    print("========================================\n")


def main():
    print("=== AI-Assisted STRIDE Threat Model Generator ===")
    print("AM Consulting | github.com/am-consulting\n")

    if len(sys.argv) > 1:
        system_description = " ".join(sys.argv[1:])
    else:
        print("Describe your system (press Enter twice when done):")
        lines = []
        while True:
            line = input()
            if line == "":
                break
            lines.append(line)
        system_description = " ".join(lines)

    if not system_description.strip():
        print("[!] No system description provided. Exiting.")
        sys.exit(1)

    result = generate_threat_model(system_description)
    print_summary(result)
    save_report(result, system_description)


if __name__ == "__main__":
    main()
